### PR TITLE
FIX Automatically create default SiteTree records for new subsites

### LINKED ISSUE #252: New subsite should automatically get a "home" page (infinite redirects otherwise)
Every SilverStripe website needs a page with the `home` URLSegment. Creating an empty subsite leads to infinite redirects when not copying structure from a template. This is hardly ideal default behaviour.

### PR DESCRIPTION
**Pull request by robbieaverill**
Resolves #252 (for SS3). For SS4 we can modify the logic slightly:

```php
SubsiteState::singleton()->withState(function (SubsiteState $newState) {
    $newState->setSubsiteId($this->ID);

    DB::quiet();
    (new SiteTree)->requireDefaultRecords();
});
```

^ in unit tests and `Subsite::createDefaultPages`.

This will create a home page at least. The logic in `SiteTree::requireDefaultRecords` uses manual SQL queries to determine whether an about us or contact page exist, so that's unlikely to work here. We get a home page at least, which was the original requirement.

### CODE REVIEW

File: code/model/Subsite.php [hunk 1]
```diff
@@ -750,9 +758,41 @@ public function validate()
     public function onAfterWrite()
     {
         Subsite::writeHostMap();
+        $this->createDefaultPages();
```
Comment (NightJar) [inline code/model/Subsite.php]: I think this can be done via `if ($this->isChanged('ID')) {` which would avoid the need for the new member property and the abstraction to the new function (although a protected function isn't really the worst thing). If this remains true (I'm 90% certain this was the case in SS3 at least) then it would make the code more readable and easier to follow.

Comment (robbieaverill) [reply code/model/Subsite.php]: It would, but I wouldn't be at all surprised if this doesn't work. The last time I tried to track field level changes during a write I had to do this individually for every field I wanted to track because the framework calls ->write() multiple times. Nevermind, let's change the API and see if the test still passes!

Comment (robbieaverill) [reply code/model/Subsite.php]: Works like a charm! Thanks for the suggestion 👍
