### PR TITLE
Fix "Column 'URLSegment' in where clause is ambiguous" when duplicating pages

### LINKED ISSUE #450: Cannot duplicate page "Column 'URLSegment' in where clause is ambiguous"
When trying to duplicate certain pages, this SiteTreeSubsites extension throws the error  `Column 'URLSegment' in where clause is ambiguous`

While unable to identify the exact cause, as this only occurs on "some" pages, I assume its something to do with Fluent as well.

Converting `DataObject::get_one` to `SiteTree::get()->filter` seems to fix it

### PR DESCRIPTION
**Pull request by cjsewell**
Fixes #450

### CODE REVIEW

File: src/Extensions/SiteTreeSubsites.php [hunk 1]
```diff
@@ -484,14 +484,7 @@ public function augmentSyncLinkTracking()
...
                         Subsite::disable_subsite_filter(true);
-                        $candidatePage = DataObject::get_one(
-                            SiteTree::class,
-                            "\"URLSegment\" = '"
-                            . Convert::raw2sql(urldecode($rest))
-                            . "' AND \"SubsiteID\" = "
-                            . $subsiteID,
-                            false
-                        );
+                        $candidatePage = SiteTree::get()->filter(['URLSegment' => urldecode($rest), 'SubsiteID' => $subsiteID])->first();
```
Comment (NightJar) [inline src/Extensions/SiteTreeSubsites.php]: This line needs to be split in order to make the linter happy :)
I suggest making the array multi-line.

Comment (cjsewell) [reply src/Extensions/SiteTreeSubsites.php]: Fixed now
